### PR TITLE
Added new translation: HU (Hungarian)

### PR DESCRIPTION
**Pull request by montlikadani**
I've translated the '#' mark too.

### CODE REVIEW

**Comment by Zedd7** [comment]
Thanks for your work, it will be added to the next update.
However, future updates may add new lines to the locale files that will then require additionnal translation. Would you mind if I @tag you in commits to request help for translation ?

**Comment by montlikadani** [comment]
Yes.

**Comment by Zedd7** [comment]
Well, then I'm not sure if merging locale_HU is a good idea as it may result in a partially translated locale file with english parts.
I will wait and see if there are chances that a future update requires new lines in locales.

**Comment by Zedd7** [comment]
1.6.10 update will add new lines to locale files and thus prevent the merging of this branch, as mentioned above.

**Comment by montlikadani** [comment]
If you think about it, do you add or not yet?

**Comment by Zedd7** [comment]
I understood that you would not be available for further translations (new lines added in upcoming updates) ?

**Comment by montlikadani** [comment]
I'll be available if you add new strings to the file.

**Comment by Zedd7** [comment]
Alright then, I will keep this open and send you the new lines when they are ready. It should only concern one command so about 5-10.

**Comment by Zedd7** [comment]
Hi @montlikadani, would you mind translating the two new lines that came with 1.6.10 snapshot 2 and are still to be translated (the other ones have been taken care of) ?

That would be lines [63](https://github.com/Zedd7/ZHorse/blame/e15a55bcdb19ef2cf80ea8290c7a2ad25dd30db9/src/main/resources/yaml/locale_HU.yml#L63) and [203](https://github.com/Zedd7/ZHorse/blame/e15a55bcdb19ef2cf80ea8290c7a2ad25dd30db9/src/main/resources/yaml/locale_HU.yml#L203)

Thank you

**Pull request merged**
